import os
os.system("sudo apt update")
os.system("sudo apt upgrade")
os.system("python3 --version")
os.system("sudo apt-get install python3-pip")
os.system("pip3 install numpy")
os.system("pip3 install opencv-python")
os.system("pip3 install pyserial")
os.system("sudo apt install fswebcam")
os.system("sudo apt install linux-tools-virtual hwdata")
os.system("sudo update-alternatives --install /usr/local/bin/usbip usbip `ls /usr/lib/linux-tools/*/usbip | tail -n1` 20")
os.system("sudo apt upgrade")
